apiVersion: apps/v1
kind: Deployment
metadata:
  name: messenger
spec:
  selector:
    matchLabels:
      name: messenger
  template:
    metadata:
      labels:
        name: messenger
    spec:
      containers:
        - name: messenger
          image: {{IMAGE}}
          envFrom:
            - secretRef:
                name: messenger
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: registry-creds
---
apiVersion: v1
kind: Service
metadata:
  name: messenger
spec:
  selector:
    name: messenger
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
