apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
spec:
  selector:
    matchLabels:
      name: posts
  template:
    metadata:
      labels:
        name: posts
    spec:
      containers:
        - name: posts
          image: {{IMAGE}}
          envFrom:
            - secretRef:
                name: posts
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: registry-creds
---
apiVersion: v1
kind: Service
metadata:
  name: posts
spec:
  selector:
    name: posts
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
