apiVersion: v1
kind: Secret
metadata:
  name: gateway
type: Opaque
stringData:
  PORT: '8080'
  USERS_SERVICE_ADDRESS: users:80
  POSTS_SERVICE_ADDRESS: posts:80
---
apiVersion: v1
kind: Secret
metadata:
  name: messenger
type: Opaque
stringData:
  PORT: '8080'
  USERS_SERVICE_ADDRESS: users:80
  REDIS_ADDR: xxxxx
  REDIS_PASSWORD: xxxxx
  REDIS_DB: '0'
---
apiVersion: v1
kind: Secret
metadata:
  name: posts
type: Opaque
stringData:
  PORT: '8080'
  MONGO_CONNECTION_STRING: xxxxx
  MONGO_DB_NAME: xxxxx
  MONGO_COLLECTION: xxxxx
---
apiVersion: v1
kind: Secret
metadata:
  name: users
type: Opaque
stringData:
  PORT: '8080'
  POSTGRES_CONNECTION_STRING: xxxxx
  TOKEN_TTL: xxxxx
  JWT_KEY: xxxxx
