apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  selector:
    matchLabels:
      name: users
  template:
    metadata:
      labels:
        name: users
    spec:
      containers:
        - name: users
          image: {{IMAGE}}
          envFrom:
            - secretRef:
                name: users
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: registry-creds
---
apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  selector:
    name: users
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
