version: '2.7'

services:

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: rapu-gateway
    environment:
      - PORT=7002
      - USERS_SERVICE_ADDRESS=rapu-users:7001
      - POSTS_SERVICE_ADDRESS=rapu-posts:7003
    ports:
      - '7002:7002'
    depends_on:
      users:
        condition: service_started
      posts:
        condition: service_started

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    container_name: rapu-users
    environment:
      - PORT=7001
      - POSTGRES_CONNECTION_STRING=postgres://postgres:postgres@rapu-users_postgres:5432/users?sslmode=disable
      - TOKEN_TTL=60m
      - JWT_KEY=qwerty123
    depends_on:
      postgres:
        condition: service_healthy

  posts:
    build:
      context: ./posts
      dockerfile: Dockerfile
    container_name: rapu-posts
    environment:
      - PORT=7003
      - MONGO_CONNECTION_STRING=mongodb://mongo:mongo@rapu-posts_mongo:27017
      - MONGO_DB_NAME=rapu
      - MONGO_COLLECTION=posts
      - MAX_POSTS_PER_PAGE=20
    depends_on:
      mongo:
        condition: service_healthy

  postgres:
    image: postgres:12.7-alpine3.14
    container_name: rapu-users_postgres
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - rapu-users_pgdata:/var/lib/postgresql/data
      - ./users/config/schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}' ]
      interval: 5s
      timeout: 10s
      retries: 10

  mongo:
    image: mongo:4.4-rc-focal
    container_name: rapu-posts_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - '27017:27017'
    volumes:
      - rapu-posts_mongodata:/data/db
    healthcheck:
      test: [ 'CMD-SHELL', 'echo', 'db.runCommand("ping").ok | mongo --quiet' ]
      interval: 5s
      timeout: 10s
      retries: 10

  redis:
    image: redis:6.2.6-alpine3.14
    container_name: rapu-messenger_redis
    ports:
      - '6379:6379'
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  rapu-users_pgdata:
    name: rapu-users_pgdata
  rapu-posts_mongodata:
    name: rapu-posts_mongodata
